# Generated by Django 4.1.1 on 2022-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rollno', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
